export const FETCH_ALBUMS_START = 'FETCH_ALBUMS_START'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUMS_FAILED'

export const SELECT_ALBUM = 'SELECT_ALBUM'
export const CLEAR_ALBUM_SELECTION = 'CLEAR_ALBUM_SELECTION'
